### ISSUE TITLE
Problem with guanghechen/rollup-plugin-copy and transform

### ISSUE THREAD

**Issue by ghost91-** [guanghechen/node-scaffolds#1]
Hey there, first of all, thank you very much for maintaining the guanghechen/rollup-plugin-copy plugin, it's a tremendous help!

However, I started running into a problem occasionally: I use a `transform` function to parse a JSON file that is being copied and make some adjustments to when it is being copied. But for some reason, when the file is pretty large, and I make a change to it and save that, I don't seem to get the whole file, it's truncated at some point. And of course that means that parsing the JSON fails. Any idea why that might be happening? The function I use as transform is this:
```js
export function convertJSONToPack(contents) {
    const jsonString = contents.toString();
    return (
        JSON.parse(jsonString)
            .map((entry) => cleanPackEntry(entry))
            .map((entry) => JSON.stringify(entry))
            .join("\n") + "\n"
    );
}
```
`cleanPackEntry` just performs some cleaning on the data, it's not relevant. It already fails on the `JSON.parse`. I also logged the contents to see what's going and and that shows that the contents are truncated.

This is the specification in my `rollup.config.js`:

```js
                {
                    src: [`packs/*.json`],
                    dest: `${distDirectory}/packs`,
                    rename: (name) => `${name}.db`,
                    transform: convertJSONToPack,
                },
```

It doesn't happen when first building, only happens in watch mode when the file is changed.

**Comment by guanghechen** [comment]
Hi @ghost91-  Thanks for your feedback, I'll deal with this as soon as possible.

To make it easier to locate the problem, can you tell me how big your JSON file is? This will also be helpful for verifying whether the subsequent fix will take effect.

**Comment by ghost91-** [comment]
It is this file: https://git.f3l.de/dungeonslayers/ds4/-/blob/master/packs/creatures.json, so 1.12 MB, apparently. You can also see all of the configuration etc. In that repo.

**Comment by guanghechen** [comment]
Hi @ghost91- , I think it works correctly now! So I made a new release `@guanghechen/rollup-plugin-copy@1.9.0-alpha.0`, can you upgrade it to confirm it works?

The code is a bit old, I refactored it and use [chokidar](https://github.com/paulmillr/chokidar) to implement watch mode, now it should have better performance (only trigger copy action for a specific file when it changes).

I did a simple test with the [big json file](https://git.f3l.de/dungeonslayers/ds4/-/blob/master/packs/creatures.json) you provided, and it looks good in my machine.

Waiting for you confirmation.

**Comment by ghost91-** [comment]
Hm, with this change, watch mode doesn't seem to function properly anymore. The first time, a file is saved after having started watch mode, it gets copied over (though the process is quite long, maybe other stuff than actually copying happens, too, like building all of the ES module code..?). And after that, saving additional changes doesn't have any effect: Doesn't trigger anything being copied.

**Comment by guanghechen** [comment]
Do you mean that when file A is modified later, A's recopy operation will not be triggered?

**Comment by ghost91-** [comment]
Exactly. Or rather, it doesn’t even matter which file of the ones tracked by the copy plug-in it is. It does work when you modify a file for the first time, but after that, modifying additional files does not trigger recopys.

**Comment by ghost91-** [comment]
If it matters, I am doing this with yarn 3, using PNP, and the rollup config is an es module (not commonjs). That may or may not have an effect on things…

**Comment by guanghechen** [comment]
> Exactly. Or rather, it doesn’t even matter which file of the ones tracked by the copy plug-in it is. It does work when you modify a file for the first time, but after that, modifying additional files does not trigger recopys.

The first time will trigger the full copy operation, and then only the modified file will be re-copied. In my opinion, this is expected behavior, and I'm curious what scenarios would trigger a recopy of an unmodified file? Is there any point in re-copying an unmodified file?

> If it matters, I am doing this with yarn 3, using PNP, and the rollup config is an es module (not commonjs). That may or may not have an effect on things…

Yes I noticed, but I don't think it matters, `@guanghechen/rollup-plugin-copy` provides modules in both `esm` and `cjs` formats.

**Comment by ghost91-** [comment]
> The first time will trigger the full copy operation, and then only the modified file will be re-copied. In my opinion, this is expected behavior, and I'm curious what scenarios would trigger a recopy of an unmodified file? Is there any point in re-copying an unmodified file?

I am not expecting all files to be copied, only the modified file is just fine. That's also what I expect. But the point is that _nothing_ is copied on subsequent changes, not even the modified file. It seems like the change isn't even properly detected or something like that, because there is no output in the console at all (while usually, when changes are detected and being processed, rollup is showing a message that this is the case).

If you want, I can create a video, showing the problem in more detail.

**Comment by ghost91-** [comment]
Here is a video:

https://user-images.githubusercontent.com/236845/154328154-299b4e9f-2d42-4da0-8b29-b1596879e70f.mp4

**Comment by guanghechen** [comment]
Hi @ghost91- , thank you for the video, it's very clear, I think I get what you mean. This is actually because that message is only output when a full copy is made, **and I will fix that**. But in fact it triggers a copy now, can you add a verbose option to rollup.config.js first to verify that the re-copying is triggered.

```diff
copy({
+    verbose: true,
    targets: [
        { src: staticFiles, dest: distDirectory },
        {
            src: [`packs/*.json`],
            dest: `${distDirectory}/packs`,
            rename: (name) => `${name}.db`,
            transform: convertJSONToPack,
        },
        {
            src: [`packs/*.json.license`],
            dest: `${distDirectory}/packs`,
            rename: (name, extension) => `${name.replace(".json", ".db")}.${extension}`,
        },
    ],
})
```

You should see a message similar to the one show below:

![image](https://user-images.githubusercontent.com/42513619/154385893-ce55dcab-aa74-426a-a2d9-ed04b65f6408.png)

**Comment by guanghechen** [comment]
I will fix the problem of message printing (copying details message should under the `copied:` line), but you need to always set verbose to `true`. Because the current implementation does not always trigger the rebuild flow of rollup, but perform the copying in a separate task ([chokidar](https://github.com/paulmillr/chokidar) is responsible for monitoring and processing it), so the notification from rollup will not always printed, that is why `verbose: true` is required.

In the current implementation, the modified files are accurately triggered to be re-copied (the full copy was always triggered in the past), which is also the key factor that I claim to have greatly improved the performance in this modification.

**Comment by guanghechen** [comment]
Do you think set the default value of `verbose` is better?

**Comment by ghost91-** [comment]
It's not about the message. While it is consistent with other stuff to have it (when you edit a source file, you also get that message, and it was actually the previous behavior), that is not the point. I can only repeat: The file is not being copied. That's why I opened the resulting file on the right in the video. You can clearly see how the content of that file changes when rollup is first started. But on subsequent changes of the file no more copies happen.

I guess I can try the verbose mode anyways to check if I see anything.

**Comment by ghost91-** [comment]
So, with verbose output, I see that _something_ is happening. But the file simply isn't written. I added some logging statements to my `transform` function to check if it is even being invoked—it is not.

**Comment by ghost91-** [comment]
OK, I just played around a bit more with it. It seems to be related to the `transform`. Without a `transform`, everything seems to be working fine. But as soon as you use something as simple as
```js
transform: (contents) => contents.toString()
```
it just doesn't work anymore.

I tried that in https://github.com/guanghechen/node-scaffolds/tree/main/playground/rollup-plugin-copy and was able to confirm the problem there, too.

**Comment by guanghechen** [comment]
ACK, I will fix it.

**Comment by guanghechen** [comment]
@ghost91-  I think I fixed it, you can try the https://github.com/guanghechen/node-scaffolds/tree/main/playground/rollup-plugin-copy it now.

 Would you mind if I put some of the data from the [creatures.json](https://git.f3l.de/dungeonslayers/ds4/-/blob/master/packs/creatures.json) under the playground?

Like this:

![image](https://user-images.githubusercontent.com/42513619/154399723-68b1b69e-2d90-4d1e-9789-50fd32610c70.png)

**Comment by guanghechen** [comment]
Wait a minute, I can now reproduce your original problem, it should be caused by frequent modification of the file, I will try to solve it.

**Comment by ghost91-** [comment]
That JSON file is licensed under CC BY-NC-SA-4.0, so you can put it in your repo under the terms of that license. I can’t provide it under a more permissive license because it is based on CC BY-NC-SA-3.0 work (you would also need to attribute the original author of that, Crhistian Kennig, see http://www.dungeonslayers.net/).

**Comment by guanghechen** [comment]
> That JSON file is licensed under CC BY-NC-SA-4.0, so you can put it in your repo under the terms of that license. I can’t provide it under a more permissive license because it is based on CC BY-NC-SA-3.0 work (you would also need to attribute the original author of that, Crhistian Kennig, see http://www.dungeonslayers.net/).

Ok, I got it, and I decided to give up on adding it.

> Wait a minute, I can now reproduce your original problem, it should be caused by frequent modification of the file, I will try to solve it.

This problem discussed here https://stackoverflow.com/a/65044648, and I think it is works now. 

It is worth mentioning that you could feel that there is a delay in re-copy, but it will eventually be executed.

Can you try it in the latest `main` branch?

**Comment by ghost91-** [comment]
It seems to working correctly in version `1.9.0`. Thanks for your help with this!
