### ISSUE TITLE
rollup-plugin-copy: watching directories doesn't work as expected

### ISSUE THREAD

**Issue by ghost91-** [guanghechen/node-scaffolds#2]
Hey there, unfortunately I just ran into another issue with the new version of `rollup-plugin-copy`. It seems like copying whole directories doesn't work correctly when in watch mode. It's copied fine on the initial build, but when changing a file inside the watched folder, nothing happens. Is that a bug or intended behavior? I am pretty sure that this is not how it worked previously.

**Comment by guanghechen** [comment]
@ghost91-  is it a new created file after the watcher started?

Can you test that use a pattern like `.../a/*` instead of `.../a` or `.../a/` to watch a directory?

**Comment by ghost91-** [comment]
No, it’s about editing an existing file. But it would be very nice if it also worked for adding new files :)

I could use a glob pattern (which does seem to have the problem that watching directories has), but it makes it more difficult to set everything up because that doesn’t seem to preserve the directory structure. I would needs to specify the directory structure in the destination. That doesn’t really work very well for nested directory structures.

**Comment by guanghechen** [comment]
> But it would be very nice if it also worked for adding new files

There is such a plan, but it will take time and may not be realized in the short term.

> I could use a glob pattern (which does seem to have the problem that watching directories has), but it makes it more difficult to set everything up because that doesn’t seem to preserve the directory structure. I would needs to specify the directory structure in the destination. That doesn’t really work very well for nested directory structures.

Hmmm, not so clear to me. Why you need to specify the destination directory structure?

And... if possible, can you play it in https://github.com/guanghechen/node-scaffolds/tree/main/playground/rollup-plugin-copy and commit the configuration that can reproduce your problem to a branch? This is very useful for me to debug and solve the issue.

**Comment by ghost91-** [comment]
I would need to specify the structure in the destination directory because it is not being preserved from a glob. It just puts all the files that match the glob directly into the destination directory, without preserving any sub folders the files might have been in.

I’ll set up an example this evening.

**Comment by ghost91-** [comment]
I added examples of the things I tried to describe in #3.

**Comment by guanghechen** [comment]
Hi @ghost91- , sorry to reply you so late (have been busy today, it's already around 10pm in my city). 

I tested your example, it doesn't trigger `copying` when modifying the `some-folder/b.json`, this is all the relevant content of this issue, right? I will fix it tomorrow.

**Comment by ghost91-** [comment]
yep, that's the issue. `c.json` is just to illustrate that files matching glob patterns will be moved directly into the destination directory but that's not necessarily an issue. It's just why glop patterns don't work well as a workaround for copying whole folders.

**Comment by guanghechen** [comment]
@ghost91-  This issue is caused by the inconsistent parsing behavior of globs between `globby` and `chokidar`. I add a preprocessing to normalize the input glob patterns into a format that both can parse to the same result.

### Good news

* [x] For newly created files, a copy operation to it is also automatically triggered.
* [x] Fix issues on using directory pattern. (The problem mentioned above in `b.json`)
* [x] Support to preserve the source structure on the output directories when used a glob pattern like `assets/data/some/**/*.json`. (The problem mentioned above in `c.json`)

Can you try it at https://github.com/guanghechen/node-scaffolds/tree/main/playground/rollup-plugin-copy or using `@guanghechen/rollup-plugin-copy@1.9.1` in your projects?

**Comment by ghost91-** [comment]
Seems to be working fine now in my projects. Thanks for your help, I really appreciate it!
