### ISSUE TITLE
Support for rollup v3 (for rollup-plugin-copy)

### ISSUE THREAD

**Issue by ghost91-** [guanghechen/node-scaffolds#4]
Hey, there, would be really cool if we could get support for rollup v3. `rollup-plugin-copy` actually seems to be working just fine, I just had to change how I import the plugin. I need to use
```js
import { copy } from "@guanghechen/rollup-plugin-copy";
```
instead of
```js
import copy from "@guanghechen/rollup-plugin-copy";`
```
This is probably related to the fact that the rollup config now is not transpiled to commonjs anymore, but loaded in node as an es module.

So I don't think there's much to do on your side, aside from declaring compatibility with rollup v3 in the package.json. At the moment, a peer dependency to `"rollup": "^2.0.0" prevents using this plugin with rollup v3.

Thanks in advance!

**Comment by guanghechen** [comment]
Hi @ghost91-,  do you mean I just need to change the dependency version from `"rollup": "^2.0.0"` to `"rollup": "^2.0.0 || ^3.0.0"`? If that is true, feel free to create a PR (I have not a rollup@3 test environment in local machine), I will review it and publish a new release as soon as possible.

PS: I haven't planned to support rollup@3 recently. It seems that it will invalidate my entire packaging toolchain (I still need to support the packaging in commonjs format), but I should take the time to complete support for rollup@3 in the future. This project is one of my core projects and will be supported for a long time.

**Comment by ghost91-** [comment]
From what I have seen, that is indeed all that is needed, at least for this particular plugin. I'll create a PR.

**Comment by guanghechen** [comment]
Hi @ghost91- , the change is already released.
