### ISSUE TITLE
merge with rollup-copy-plugin?

### ISSUE THREAD

**Issue by thorsent** [guanghechen/node-scaffolds#8]
@guanghechen, it looks like you're actively maintaining this repo with very useful and important updates. Have you and @vladshcherbin considered adding you as a maintainer to the main repo so that you can get your changes in and the whole world can benefit?

**Comment by guanghechen** [comment]
Hi @thorsent , thank you for using the code I've written. However, I must admit that I currently don't have much time to maintain open-source projects. This is a monorepo, and I only occasionally update some dependencies, and unfortunately, I may not be able to promptly address bugs. I appreciate your suggestion, but at the moment, I don't have any plans to maintain the rollup-copy-plugin.

**Comment by thorsent** [comment]
Thanks for at least keeping this up for us to use :)
